name: Node.js Package

on:
  release:
    types: [created]
  workflow_dispatch:

jobs:
  publish-gpr:
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
    steps:
      - uses: actions/checkout@v4
      
      - uses: actions/setup-node@v4
        with:
          registry-url: 'https://npm.pkg.github.com/'
          node-version: 'lts/*'
          token: '${{ secrets.GITHUB_TOKEN }}'

      - run: cd src && npm ci

      - run: cd src && npm run build

      - run: cd src && npm publish
        env:
          NPM_CONFIG_TOKEN: ${{secrets.GITHUB_TOKEN}}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
