name: Node.js Package

on:
  release:
    types: [created]
  workflow_dispatch:

jobs:
  publish-gpr:
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
    env:
        NPM_CONFIG_TOKEN: ${{secrets.GITHUB_TOKEN}}
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - uses: actions/checkout@v4
      
      - uses: actions/setup-node@v4
        with:
          registry-url: 'https://npm.pkg.github.com/'
          token: ${{ secrets.GITHUB_TOKEN }}
          always-auth: true

      - run: npm ci
        working-directory: ./src

      - run: npm run build
        working-directory: ./src

      - run: npm publish
        working-directory: ./src
